-- Database export: test
-- Date: 2026-06-12 12:19:37
-- Generated by DBX

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `cart_item` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '商品名称',
  `price` decimal(13,4) NOT NULL DEFAULT '-1.0000' COMMENT '单价',
  `amount` int(11) NOT NULL DEFAULT '-1' COMMENT '数量',
  `subtotal` decimal(13,4) NOT NULL DEFAULT '-1.0000' COMMENT '小计',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='cart_item';

INSERT INTO `cart_item` (`id`, `name`, `price`, `amount`, `subtotal`) VALUES
(1, 'iPhone 15 Pro Max', '9999.0000', 4, '39996.0000');

CREATE TABLE `product` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '商品编号',
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商品名称',
  `price` decimal(10,2) NOT NULL COMMENT '商品价格',
  `color` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商品颜色',
  `size` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商品尺寸',
  `stock` int(11) NOT NULL COMMENT '商品库存',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品信息表';

INSERT INTO `product` (`id`, `name`, `price`, `color`, `size`, `stock`) VALUES
(1, 'iPhone 15 Pro Max', '9999.00', '黑色', '6.7英寸', 50),
(2, '华为 Mate 60 Pro', '6999.00', '青色', '6.82英寸', 30),
(3, '小米 14 Ultra', '6499.00', '白色', '6.73英寸', 25),
(4, 'OPPO Find X7 Ultra', '5999.00', '蓝色', '6.82英寸', 20),
(5, 'vivo X100 Pro', '5499.00', '红色', '6.78英寸', 15),
(6, '三星 S24 Ultra', '8999.00', '紫色', '6.8英寸', 10),
(7, '一加 12', '4799.00', '绿色', '6.82英寸', 40),
(8, '荣耀 Magic6 Pro', '5699.00', '灰色', '6.8英寸', 35),
(9, '真我 GT5 Pro', '3999.00', '橙色', '6.78英寸', 45),
(10, '魅族 21 Pro', '4999.00', '粉色', '6.79英寸', 18);

SET FOREIGN_KEY_CHECKS = 1;
